### ISSUE TITLE
Compiling Error

### ISSUE THREAD

**Issue by skzidan** [Marsaaaaaaa/python_ow2_paste#1]
1. Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0103	The name 'algo_speed' does not exist in the current context	ClassLibrary1	D:\Extras\themes\python_ow2_paste-main\DLL\ClassLibrary1\Class1.cs	77	N/A

2.Severity	Code	Description	Project	File	Line	Suppression State
Warning		The referenced component 'System.Security.AccessControl' could not be found.	ClassLibrary1			

3. Severity	Code	Description	Project	File	Line	Suppression State
Warning		The referenced component 'InputInterceptor' could not be found.	ClassLibrary1

**Comment by Marsaaaaaaa** [comment]
1. has been fixed
2. and 3. you need to add the paths to the files inside the solution references
