### ISSUE TITLE
ClassLibrary1.dll error

### ISSUE THREAD

**Issue by Lyssu** [Marsaaaaaaa/python_ow2_paste#5]
System.IO.FileNotFoundException: Unable to find assembly 'C:\Users\xx\Desktop\xx\DLL\ClassLibrary1\ClassLibrary1.dll'.
   em Python.Runtime.CLRModule.AddReference(String name)
   
   
   how to resolve?

**Comment by Marsaaaaaaa** [comment]
have you built the dll from the c# solution and placed it in the referenced directory?
